# Modify name if deploying multiple instances
name = "sub-box"

main = ".open-next/worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

# [placement]
# mode = "smart"

# Environment variables
# Modify these to use the correct environment variables
[vars]
ADMIN_USERNAME = "xuelang007"
ADMIN_PASSWORD = "niukai594521Ab" # Change this to a secure password
JWT_SECRET = "Tos6u4bP2nGzCjuH16Lhez" # Change this to a secure secret key
SESSION_TAG = "0"
SESSION_DURATION = "7d"
DEPLOY_TARGET = "cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "sub-box" # Change this to the name of your D1 database
database_id = "bd7ae93c-6266-4a8e-b9de-fba55caf396e" # wrangler d1 info <YOUR_DATABASE_NAME>

[observability.logs]
enabled = true

# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "prod-sub-box-next-inc-cache"
